name = "baqsha-worker"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "baqsha-worker-prod"

[[d1_databases]]
binding = "DB"
database_name = "baqsha-ai"
database_id = "cbcc44ed-f9bd-4a03-ad13-82117b2787a9"

[[kv_namespaces]]
binding = "CACHE"
id = "06f9bfa657974faeb4d6598c88bf6b0e"
preview_id = "your-preview-kv-id"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "baqsha-images"

[ai]
binding = "AI"

[vars]
APP_NAME = "Baqsha.AI"
CORS_ORIGIN = "https://baqsha-ai.nurbakhyt.pages.dev"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
